name: Sanity Check Action

on: [push]

jobs:
  install-dependncies:
     runs-on: windows-latest
     steps:
       - name: Install node
       - uses: actions/checkout@71899b7d7d90c887a0de82b852fcbdf84c375586
       - uses: actions/setup-node@v2
         with:
           node-version: 14
       - name: Execute test
         run: |
          npm install
          npx run teste2e