name: Sanity Check Action

on: [push]

jobs:
  install-dependncies:
    runs-on: windows-latest
    steps:
      - name: Checkout to latest commit
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: run the test
        run: |
          yarn install
          yarn run teste2e
